### ISSUE TITLE
msmc2 compilation problem 

### ISSUE THREAD

**Issue by potw** [stschiff/msmc2#1]
Dear Stephan,

I've tried to compile msmc2 but I get an error:

sbipao@axon:~/msmc2-master$ make
/opt/shared/software/dmd2/linux/bin64/dmd -O -L-lgsl -L-lgslcblas -release -odbuild/test -ofbuild/release/msmc2 model/data.d model/gsl_matrix_vector.d model/propagation_core.d model/psmc_hmm.d model/psmc_model.d model/stateVecAllocator.d model/stateVec.d model/time_intervals.d model/transition_rate.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
model/data.d(69): Error: undefined identifier file, did you mean struct File?
maximization_step.d(41): Error: undefined identifier format
make: *** [build/release/msmc2] Error 1

I think this error may be related to the dmd version like in the case for msmc1 (one of the closed threads in the github discussion group that I started). The dmd in our cluster is:

sbipao@axon:/opt/shared/software/dmd2/linux/bin64$ ./dmd -v
DMD64 D Compiler v2.067.1

Thanks for looking into this,
Pablo

**Comment by stschiff** [comment]
I just fixed this yesterday. Please pull the latest version and try again
