### ISSUE TITLE
Population Structure 

### ISSUE THREAD

**Issue by stsmall** [stschiff/msmc2#10]
Hi Stephan,
I didnt know where to post this, but it is a question not really an issue. I thought that others may have the same question, so here goes. The papers by Mazet 2015/2016, raise a concern in uses of MSMC and PSMC for interpreting population size changes when not accounting for population structure. While Mazet raises this issue he really doesnt provide a valid solution. Do you have any thoughts or advice on addressing this issue with either the MSMC models or other software? Would ABC w/model selection, such as testing constant size with migration versus population size changes with no migration be appropriate? There seems to be an anomalous zone where certain amounts of migration and pop size change are both a "good" fit.
thank you,
scott

**Comment by stschiff** [comment]
I think this problem is hard to solve in general. I am working on something in that direction, but I'm not sure whether it will solve the problem you describe. Ultimately, MSMC measures coalescence rates, and it doesn't care how we interpret those.
