### ISSUE TITLE
citation of msmc2

### ISSUE THREAD

**Issue by swamidass** [stschiff/msmc2#12]
If msmc2 is used in a publication, how would you like it cited? How would you summarize the salient differences between msmc? Or would you prefer we did not to do published work with msmc2 till it is published?

**Comment by stschiff** [comment]
You can cite Malaspinas et al. 2016 if you want to use MSMC2 at this point, but we are still in active development of the tool and it will change further. There is a publication in preparation currently about this as well.

Stephan
