### ISSUE TITLE
multi threads

### ISSUE THREAD

**Issue by laurabuggiotti** [stschiff/msmc2#14]
Hi,

Im a user in HPC and im currently using msmc to cross population analysis. 
As im running out of memory, I need to use mpirun to be able to run ihte job in more than one node, however i get an error and the job get killed.
Do you reckon msmc2 can be run using the mpirun?

`mpirun msmc2 -t 100 -o HolKho.cross.20vs20h_msmc_output -I 0-1,0-2.... -s  Chr1.HolKho.msmcinput.txt ${input}/Chr2.HolKho....`

Thanks for your support,
Laura

**Comment by stschiff** [comment]
Hi Laura,
I have no idea whether `mpirun` will work in this case. How many cross-pairs are you trying to run? It shouldn't run out of memory for any reasonable number of haplotypes, say up to 12 or so. MSMC2 was not designed to go much higher than that. Having said that, I have so far only used it on human data. It's possible that you can run on more if you have data with shorter chromosomes.

**Comment by laurabuggiotti** [comment]
Hi,

thanks for answering. I have been using 20 haplotypes per population (400 cross pairs) and it worked fine for some of the breeds (im working on cattle and having 29 chrs), but one of them in which i get the need of using more memory and thus mpirun. 
Do you reckon i could run it per chromosome and then merge it?

**Comment by stschiff** [comment]
Well, that would give you lower resolution, and it’s not obvious how to merge results.
I would reduce the number of pairs. Chances are that your results won’t change much from 12 up to 20 haplotypes anyway.

Stephan
