### ISSUE TITLE
msmc2 -I 4,5,6,7 error

### ISSUE THREAD

**Issue by dzaccook** [stschiff/msmc2#15]
Hi,

I want to do cross-population analysis using MSMC2, I have generate a combined input file with eight haplotypes like this (two from each population)，
1       567        38      TTTTGGGG
1       573         6       AAAACCCC
1       11355     64     CCCCAAAA
1       11433     5       TTTTCCCC
..........
When I run "msmc2 -t 19 -s -I 0,1,2,3 -o WEU.msmc2.out chr.txt chr2.txt......", it works, but when I run "msmc2 -t 19 -s -I 4,5,6,7 -o CEU.msmc2.out chr.txt chr2.txt.....", it reported an error. the log was,
core.exception.RangeError@msmc2.d(139): Range violation
----------------
??:? _d_arraybounds [0x5b9a3f]
??:? msmc2.__array [0x57d06c]
??:? void msmc2.parseCommandLine(immutable(char)[][]).handleIndices(immutable(char)[], immutable(char)[]) [0x574c11]
??:? bool std.getopt.handleOption!(void delegate(immutable(char)[], immutable(char)[])).handleOption(immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), ref immutable(char)[][], ref std.getopt.configuration, bool) [0x5787b5]
??:? void std.getopt.getoptImpl!(immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x57a737]
??:? void std.getopt.getoptImpl!(immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x579f9e]
??:? void std.getopt.getoptImpl!(immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x579730]
??:? void std.getopt.getoptImpl!(immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x578d62]
??:? void std.getopt.getoptImpl!(immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x57837d]
??:? void std.getopt.getoptImpl!(immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x577f0c]
??:? void std.getopt.getoptImpl!(immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x577496]
??:? void std.getopt.getoptImpl!(immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x576a10]
??:? void std.getopt.getoptImpl!(std.getopt.config, immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getoptImpl(ref immutable(char)[][], ref std.getopt.configuration, ref std.getopt.GetoptResult, ref std.getopt.GetOptException, std.getopt.config, immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x576556]
??:? std.getopt.GetoptResult std.getopt.getopt!(std.getopt.config, immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*).getopt(ref immutable(char)[][], std.getopt.config, immutable(char)[], ulong*, immutable(char)[], double*, immutable(char)[], double*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], uint*, immutable(char)[], bool*, immutable(char)[], immutable(char)[]*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], bool*, immutable(char)[], void delegate(), immutable(char)[], ulong*, immutable(char)[], bool*, immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], void delegate(immutable(char)[], immutable(char)[]), immutable(char)[], double*, immutable(char)[], bool*) [0x576235]
??:? void msmc2.parseCommandLine(immutable(char)[][]) [0x5740cb]
??:? _Dmain [0x573d83]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5bbd22]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5bbc78]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x5bbcde]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5bbc78]
??:? _d_run_main [0x5bbbd5]
??:? main [0x57d0d5]
??:? __libc_start_main [0x7351eb14]

Can you give me some help?
Thank you,
zac

**Comment by stschiff** [comment]
Hmm, can you email me your input file, please?

Stephan

**Comment by dzaccook** [comment]
Hi,
Please give me a mail address? I can not open the google....

**Comment by dzaccook** [comment]
Hi,
Please give me a mail address? I can not open the google....

**Comment by stschiff** [comment]
Sorry: schiffels@shh.mpg.de <mailto:schiffels@shh.mpg.de>

Thanks,
Stephan

**Comment by stsmall** [comment]
Hi Stephan,
I seem to be having the exact same error as @dzaccook.
while this works: msmc2 -r 2.5 -t 10 --skipAmbiguous -I 0,1,2,3 -o moz.Cc.msmc2.out 3R.3Moz.2Tan.3Ug.msmc2-Cc.in
this gives the same range error as above: msmc2 -r 2.5 -t 10 --skipAmbiguous -I 6,7,8,9 -o tan.Cc.msmc2.out 3R.3Moz.2Tan.3Ug.msmc2-Cc.in

I also tried remove ambig sites manually, but the error is the same. I can also send my file if it would be helpful.
thanks,
@stsmall

**Comment by stschiff** [comment]
OK, I fixed it. It was a quite stupid bug, and I don't know why it hasn't shown up before. Thanks for reporting it. You can find the new release under the releases tab. I will still upload binaries later.

**Comment by dzaccook** [comment]
Thank you, it works now.

**Comment by stsmall** [comment]
yes, thank you Stephan. Works for me as well
