### ISSUE TITLE
The much higher Ne results generated by MSMC2 than that in PSMC

### ISSUE THREAD

**Issue by yongzhiyang2012** [stschiff/msmc2#16]
Hi,
I have used the MSMC2 to create the population demographic hsitory by 2/4/8-haplotypes. But all the results showed a much higer Ne (more than twice) than that infered by PSMC. Is there has some way to phase the results or some explanation for this?

**Comment by stschiff** [comment]
Well, it does look pretty enormous. Try plotting on a log-scale… these extremely recent runaway effects can be unrealistic, but they do suggest pretty strong growth.

Stephan
