### ISSUE TITLE
Tutorial: output looks different

### ISSUE THREAD

**Issue by pstokespmb** [stschiff/msmc2#17]
Thanks for writing such a great program! I have worked through your tutorial, but I am getting slightly different output. Specifically, AFR and EUR effective population size seems to have been dampened. Your example shows the populations reaching ~6e+4, while mine make it to ~4e+4. Do you know why this could have happened?

![screen shot 2018-10-19 at 11 11 23 am](https://user-images.githubusercontent.com/32311548/47236291-8aaac980-d390-11e8-8883-f08ce3956dd2.png)

![screen shot 2018-10-19 at 11 11 50 am](https://user-images.githubusercontent.com/32311548/47236304-8ed6e700-d390-11e8-9da2-a71da7c61aed.png)

**Comment by stschiff** [comment]
Seems you have a factor 2 wrong in the population size. 

Stephan

**Comment by pstokespmb** [comment]
Ahhh yes, I see that. Do you have any suggestions as to why the tutorial would output the difference? As in, why would it output something different from what the tutorial shows?

Thanks for your help!

**Comment by pstokespmb** [comment]
Could these small differences be due to the MSMC vs MSMC2 differences?
