### ISSUE TITLE
Tutorial: unrecognized option

### ISSUE THREAD

**Issue by pstokespmb** [stschiff/msmc2#18]
Hi there! I was working through the tutorial and I encountered the following error after using:

msmc2 -t 4 -I 0,1,4,5 -P 0,0,1,1 -s -p 1*2+15*1+1*2 -o $OUTDIR/AFR_EUR.msmc2 $INPUTDIR/EUR_AFR.chr1.multihetsep.txt

error in parsing command line: std.getopt.GetOptException@/projects1/clusterhomes/schiffels/software/dmd2/src/phobos/std/getopt.d(620): Unrecognized option -P

**Comment by stschiff** [comment]
Hi, yes, that needs to be updated. You now have to use -I 0-4,0-5,1-4,1-5 and no -P anymore.

I’ll update it, sorry.

Stephan
