### ISSUE TITLE
Affect of rho/mu ratio in reconstructing histories

### ISSUE THREAD

**Issue by fredericlabbe** [stschiff/msmc2#23]
Hi Stephan,

I am currently using MSMC2 to inferred the population demographic history of mosquito species. I used the -r option to change the rho/mu rate to that suggested in a previous study, which was approx 7. The results for recent time epochs were consistent with estimates from StairwayPlot but the trajectories did not overlap or join around the estimated species divergence times (MRCA) as I expected.

![MSMC2_All_All_1stBestInd_output_final](https://user-images.githubusercontent.com/25242740/60301263-e86bba00-98fe-11e9-8d3a-0bfe7382494a.jpg)

I used data from all chromosomes, which had ~4,000,000 SNPs on average (i.e. ~17,000,000 SNPs per species on average). I also only used 1 individual but the pattern is consistent when using other individuals. All other options are default.

Could this result be due to the high rho/mu ratio?
I am not quite clear on how it would affect the estimation.

Thanks in advance for your help!
Fred

**Comment by stschiff** [comment]
I have to close this, as this is a complex question and to answer it would involve some simulations to experiment with high rho/mu ratios. For humans this is much lower, so this is outside of my expertise.
