### ISSUE TITLE
msmc-input

### ISSUE THREAD

**Issue by dcf774967** [stschiff/msmc2#25]
Hi, everyone!
when i use msmc.
It's give me " Haplotype index exceeds number of haplotypes in datafile".

The input file:
`<chr1A_part1     190825  273     CAACAA
chr1A_part1     11588243        9446    GACCACATCGGCCTCGTGACCACATCGGCCTCGT
chr1A_part1     23877063        8727    GTTGTT
chr1A_part1     26200727        1096    AATAAT
chr1A_part1     26200730        3       ACTTACTT
chr1A_part1     26200731        1       GAATGAAAGAATGAAA
chr1A_part1     45844315        9853    CA
chr1A_part1     45844329        14      TGACTCGCAAGGTTAGTGCTGACTCGCAAGGTTAGTGC
chr1A_part1     58939483        6441    CT
chr1A_part1     63511145        2397    CA
chr1A_part1     91505100        11507   AC
chr1A_part1     102772581       5193    AG
chr1A_part1     104684808       558     TGTG
chr1A_part1     140356838       14652   ATCACCAGTACCGGTTGCAGCAAAGAGCGCATCACAGATTGATCACCAGTACCGGTTGCAGCAAAGAGCGCATCACAGATTG
chr1A_part1     144185802       1787    ATTTACCCGACTCCAGTAGATTTACCCGACTCCAGTAG
chr1A_part1     149610591       2323    TGTGGCTGATCCGCGTGCCGCGCATGTTGCTCGGTGCGCTGGTCGGTGCCGGGTTAGCGTTGATTGGTGTGGCTGATCCGCGTGCCGCGCATGTTGCTCGGTGCGCTGGTCGGTGCCGGGTTAGCGTTGATTGG
chr1A_part1     153854478       2269    AACGGAACGG
chr1A_part1     175187092       8967    ATAT
chr1A_part1     180379540       2174    AGCCCTGGTCTGCCTGGCCAACATGGCGCACCTGGCAGCCCTGGTCTGCCTGGCCAACATGGCGCACCTGGC
chr1A_part1     184144032       2457    CGGCAGCGGCAG
chr1A_part1     207555182       9823    GTTTGAACTCCAGCGGCAACACGCCCATGCCCACCAGGTTGGTGCGGTGGATGCGCTCGAAACCTTCGGCGACGATGTTTGAACTCCAGCGGCAACACGCCCATGCCCACCAGGTTGGTGCGGTGGATGCGCTCGAAACCTTCGGCGACGAT
chr1A_part1     237257636       11899   CCGCCG
chr1A_part1     248571467       4604    TCGGCAAATTCGGCAGAAAACCCATGAAACTCGGCAAATTCGGCAGAAAACCCATGAAAC
chr1A_part1     257976293       3757    TACAAGTACAAG
chr1A_part1     265011809       2947    AGAG
chr1A_part1     302258882       15044   CTTTAAACTTTAAA
chr1A_part1     320167446       7294    CAAGCGCAAGCG
chr1A_part1     395436827       29799   AATTTTGCATAATTTTGCAT
chr1A_part1     410847709       5021    TC
chr1A_part1     410847719       10      CT
chr1A_part1     419483584       3648    GT
chr1A_part1     434961272       6337    GGCCGGCC
chr1A_part1     435444002       257     AACACCGTCACAACACCGTCAC
chr1A_part1     435867883       262     CAGGCTGCCGGGGTATACCGGCTCGTAGTAACCGGTGATCAGGCTGCCGGGGTATACCGGCTCGTAGTAACCGGTGAT
chr1A_part1     445750247       3728    CATGATCACCAGGCTGCCGGCCTTGGCGCCGTTCATGATCACCAGGCTGCCGGCCTTGGCGCCGTT
>`

What can i do to make msmc run and get right answer?

**Comment by stschiff** [comment]
You have vastly different number of haplotypes at each location. That's illegal. You need a fixed number of haplotypes in each location.
