### ISSUE TITLE
msmc 

### ISSUE THREAD

**Issue by cfhj** [stschiff/msmc2#27]
Dear @stschiff
I'm new for msmc2, and when i'm trying i meet an error

error in parsing command line: object.Exception@model/data.d(112): nr of called sites must be positive!

Thanks

**Comment by stschiff** [comment]
As explained [here](https://github.com/stschiff/msmc/blob/master/guide.md) the third column of the input file must be positive and can't be zero or negative. There must always be at least one site difference to the next segregating site.
