### ISSUE TITLE
Number of populations

### ISSUE THREAD

**Issue by kmanoharan01** [stschiff/msmc2#28]
Hi,

Sorry If it is a basic question, I have been struggling with this issue for a long time.

If one has to estimate divergence time for more than two population, one should generate_multihetsep files two populations at a time or generate_multihetsep files all population at once?

Thanks,
Manoharan

**Comment by biozzq** [comment]
Hi, I think it should be two populations at a time.

**Comment by kmanoharan01** [comment]
Hi, Thanks, so much for your reply.
