### ISSUE TITLE
 MSMC2: Cross Coalescent divergence time

### ISSUE THREAD

**Issue by kmanoharan01** [stschiff/msmc2#29]
Hi 

I tried following "MSMC and MSMC2: The Multiple Sequentially Markovian Coalescent" paper msmc2 pipeline specifically using bamcaller, shapeit for phasing and generate_multihetsep.py (chr1 to chr22) for two of human population from Malaspinas et al (2016), ie. WCD01 and CAI01: Effective population size seems to be ok but cross coalescence is not correct could you please let me what might be wrong? 

Effective population size:

![effective_size](https://user-images.githubusercontent.com/31337106/119082254-0980ab00-ba41-11eb-92e5-85f12fec375b.png)

![plot_zoom_png](https://user-images.githubusercontent.com/31337106/119082008-88c1af00-ba40-11eb-8b73-8794cf5ac7f6.png)

**Comment by biozzq** [comment]
Hi, it better for you to provide your detailed commands here.

**Comment by kmanoharan01** [comment]
Hi

Thank you for your quick reply. Please find below commands:

## Same below commands followed for CAI01 sample ###

samtools depth -r 20 WCD01.bam | awk '{sum += $3} END{print sum/NR}'

for i in {1..22};do

samtools mpileup -B -q 20 -Q 20 -C 50 -g -r ${i} -f /data2/collaborate/FirstAustralians/hs37d5_1000GP/hs37d5.fa WCD01.bam | bcftools call -c -V indels | ~/programs/msmc-tools/bamCaller.py --legend_file /data5/users/s5001788/myproj_14samples/pama/vcfs/100Aus/shapeit/ref_panel/test/1000GP_Phase3/1000GP_Phase3/1000GP_Phase3_chr${i}.legend.gz 75 WCD01_mask.chr${i}.bed.gz | bgzip -c > WCD01_output_chr${i}.vcf.gz;

done

#!/bin/bash

module load bioinformatics/samtools/1.3.1

for CHR in {1..22}; do
    UNPHASED_VCF=WCD01_output_chr${CHR}.vcf.gz
    UNPHASED_VCF_NOMAS=WCD01.chr${CHR}.noMultiAllelicSites.vcf.gz
    GEN_MAP=/data5/users/s5001788/myproj_14samples/pama/vcfs/100Aus/shapeit/ref_panel/test/1000GP_Phase3/1000GP_Phase3/genetic_map_chr${CHR}_combined_b37.txt
    REF_HAPS=/data5/users/s5001788/myproj_14samples/pama/vcfs/100Aus/shapeit/ref_panel/test/1000GP_Phase3/1000GP_Phase3/1000GP_Phase3_chr$CHR.hap.gz
    REF_LEGEND=/data5/users/s5001788/myproj_14samples/pama/vcfs/100Aus/shapeit/ref_panel/test/1000GP_Phase3/1000GP_Phase3/1000GP_Phase3_chr$CHR.legend.gz
    REF_SAMPLE=/data5/users/s5001788/myproj_14samples/pama/vcfs/100Aus/shapeit/ref_panel/test/1000GP_Phase3/1000GP_Phase3/1000GP_Phase3.sample
    LOG_ALIGN=WCD01.chr$CHR.alignments
    EXCLUDE_LIST=$LOG_ALIGN.strand.exclude
    LOG_MAIN=WCD01.chr$CHR.main
    
    PHASED_HAPS=WCD01.chr$CHR.phased.haps.gz
    PHASED_SAMPLE=WCD01.chr$CHR.phased.samples
    PHASED_VCF=WCD01.chr$CHR.onlyPhased.vcf
    
    LOG_CONVERT=WCD01.chr$CHR.convert
    FINAL_VCF=WCD01.chr$CHR.phased.vcf.gz
    
	tabix -f $UNPHASED_VCF
    
	#Preparation
	bcftools view -M 2 -O z $UNPHASED_VCF > $UNPHASED_VCF_NOMAS
	~/programs/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin/shapeit -check -V $UNPHASED_VCF_NOMAS -M $GEN_MAP --input-ref $REF_HAPS $REF_LEGEND $REF_SAMPLE --output-log $LOG_ALIGN

	#Main run
	#~/programs/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin/shapeit -V $UNPHASED_VCF_NOMAS -M $GEN_MAP --input-ref $REF_HAPS $REF_LEGEND $REF_SAMPLE -O $PHASED_HAPS $PHASED_SAMPLE --exclude-snp $EXCLUDE_LIST --no-mcmc --output-log $LOG_MAIN
	
	 ~/programs/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin/shapeit -V $UNPHASED_VCF_NOMAS -M $GEN_MAP --input-ref $REF_HAPS $REF_LEGEND $REF_SAMPLE -O $PHASED_HAPS $PHASED_SAMPLE --exclude-snp WCD01.chr$CHR.alignments.snp.strand.exclude --no-mcmc --output-log WCD01.chr$CHR.main
	

    ~/programs/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin/shapeit -convert --input-haps $PHASED_HAPS $PHASED_SAMPLE --output-vcf $PHASED_VCF --output-log $LOG_CONVERT

	#Zipping and indexing
	bcftools view -O z $PHASED_VCF > $PHASED_VCF.gz
	tabix -f $PHASED_VCF.gz

	PHASED_VCF=WCD01.chr$CHR.onlyPhased.vcf.gz

	#Merging phased and unphased vcfs, keeping all unphased sites from the original vcf, but replacing the phased ones.
	bcftools merge --force-samples $UNPHASED_VCF $PHASED_VCF | awk -F "\t" 'BEGIN {ofs="\t"}
        $0 ~ /^#CHROM/ {print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}
        $0 !~ /^#/ {
            if(substr($11, 1, 3) != "./.")
                $10 = $11
            print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
        }' | bgzip > $FINAL_VCF

done

########### Final MSMC2 run ####



for i in {1..22}; do   python3 ~/programs/msmc-tools/generate_multihetsep.py --chr ${i} --mask cai/cai01/CAI01_mask.chr${i}.bed.gz --mask wcd/wcd1/WCD01_mask.chr${i}.bed.gz --mask hs37d5_chr${i}.mask.bed.gz cai/cai01/CAI01.chr${i}.phased.vcf.gz wcd/wcd1/WCD01.chr${i}.phased.vcf.gz > cai_wcd/generate_multihetsep_chr${i}_cai_wcd.txt; done


msmc2 -t 12 -s -o wcd.msmc2 -I 2,3 generate_multihetsep_chr*_cai_wcd.txt

msmc2 -t 12 -s -o cai.msmc2 -I 0,1 generate_multihetsep_chr*_cai_wcd.txt

msmc2 -t 10 -I 0-2,0-3,1-2,1-3 -s -o cai_wcd generate_multihetsep_chr*_cai_wcd.txt

python3.7 ~/programs/msmc-tools/combineCrossCoal.py cai_wcd.final.txt cai.msmc2.final.txt wcd.msmc2.final.txt > combined_cai_wcd.final.txt

Thanks

**Comment by biozzq** [comment]
Sorry, @kmanoharan01 , I can not find any apparent error in your codes, I think we need the help from @stschiff . More, you can change to use any other samples to repeat this analysis again.

Best,
Zheng zhuqing

**Comment by kmanoharan01** [comment]
Thanks, very @biozzq for your help. I tried few samples earlier divergence time had a similar pattern, so repeated with WCD01 and CAI01. Do not know what is really wrong. Would really appreciate if @stschiff give his comments on this.

**Comment by stschiff** [comment]
Hi @kmanoharan01. I can't see any obvious problem, and the result you see in the cross coalescence rate has as its simplest explanation that the two populations you're analysing are simply too recently diverged. It's a bit weird to get such a non-monotonicity, but the fact that it's nowhere near zero certainly suggests that there has been substantial gene flow until very recently. Would that be possible in this case?

**Comment by biozzq** [comment]
Dear @kmanoharan01 ,

I hope you can take some time to help us to clear the doubt about the latest guide https://github.com/stschiff/msmc-tools/blob/master/msmc-tutorial/guide.md. I have opened an issue here https://github.com/stschiff/msmc-tools/issues/39

Thank you for you time,
Sincerely
Zheng zhuqing

**Comment by kmanoharan01** [comment]
Hi @stschiff 

Thanks very much for your reply,

But when I used all sites phased VCFs from Malaspinas et al 2016 study, I am getting the results reported in Malaspinas et al 2016.

![div_Malasp2016](https://user-images.githubusercontent.com/31337106/119827022-03f0fc80-bf3c-11eb-9226-cb47ef6c91e8.png)

However, when I use MSMC2 pipeline, I am getting below result. Hence, I am not sure where is wrong:

![image](https://user-images.githubusercontent.com/31337106/119827120-1e2ada80-bf3c-11eb-98a1-acc22be1f18a.png)

Any suggestion will be appreciated?

**Comment by stschiff** [comment]
I don't understand what you mean by "MSMC2-Pipeline". Obviously phasing is an art by itself. I wouldn't go so far to claim that what I described in that back chapter is the last word on it. It's definitely tricky to phase data with high accuracy.

So, why can't you use the phased data from Malaspinas? I don't even know what data you're running on.

In any case: I can't really help you with getting the phasing right. We've included that pipeline in that chapter to get people started at all, but as I said. Phasing is a rabbit hole on its own and you will need to consult other experts or forums to get this right. I can only support using MSMC on whatever input data you have, not all the complex preprocessing involved, like phasing.

**Comment by kmanoharan01** [comment]
Hi,

A bit different question from the post; 

Does MSMC2 provide reliable split timing for less than 10,000 years now? 

How many number of samples do we need, to get the correct timing if the split time is less than 10,000 years ago? Is it 16 haplotypes (for samples per population)?

Will close this post after this.

Thanks,

**Comment by stschiff** [comment]
I haven't evaluated the power specifically for <10,000 years for humans. You can have a look into [this paper](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008552) where we use MSMC data to fit a isolation-migration model, and there in Figure 7 you can see some examples of human populations that split less than 10000 years ago. This is based on 4 haplotypes per population. Perhaps you can explore how far you can push it with more haplotypes, using simulations for example.

**Comment by biozzq** [comment]
Hi @stschiff 

I tried to use MSMC-IM, but it failed https://github.com/wangke16/MSMC-IM/issues/6. I raised the issue on github, hope you can help me by any chance. Thank you very much.

Best regards,

**Comment by kmanoharan01** [comment]
Thank you very much for your reply..
