### ISSUE TITLE
number haplotypes

### ISSUE THREAD

**Issue by kmanoharan01** [stschiff/msmc2#31]
Hi

Just wondering what is the Maximum number of haplotypes we can use for divergence time in msmc and msmc2?

Thanks,
Mano

**Comment by stschiff** [comment]
In MSMC2 it's limited by computational time only. We have tried 8 vs 8 haplotypes, so 16 in total, which took several days to complete, I think. In MSMC you shouldn't go beyond 4 and 4, so 8 in total.

**Comment by kmanoharan01** [comment]
Thank you.
