### ISSUE TITLE
minimum covergae for running MSMC2

### ISSUE THREAD

**Issue by AliceIob** [stschiff/msmc2#34]
Hello, 
I was wondering what's the minimum sequencing coverage required for running MSMC and getting reliable results. 
I have sequence data with coverage 3-5X, is that enough?

Thanks

**Comment by stschiff** [comment]
Hi.

Not really. See here: https://link.springer.com/protocol/10.1007%2F978-1-0716-0199-0_7 <https://link.springer.com/protocol/10.1007/978-1-0716-0199-0_7>

Best,
Stephan
