### ISSUE TITLE
Phase without reference panel

### ISSUE THREAD

**Issue by mbrieuc** [stschiff/msmc2#37]
Good morning,
I am trying to use msmc2 with a non model species for which we do not have a reference panel for phasing, only population data. But the tutorial/example only shows the scenario when phasing with a reference panel and merging the individuals after. Would it be possible to have an example using msmc2 without the use of a reference panel? Because I'm a bit lost about how to proceed. 
Thanks a lot
Best regards

**Comment by stschiff** [comment]
You need phased data if you want to analyse multiple genomes. I can't support how to phase... that needs to be decided on a case by case basis. In humans, we typically use reference panels to do that, or related individuals.

You can also run MSMC2 on a single unphased diploid genome. Then it's pretty similar to PSMC. See also here for help:

https://link.springer.com/protocol/10.1007%2F978-1-0716-0199-0_7
