### ISSUE TITLE
Cross-coalescence rate query

### ISSUE THREAD

**Issue by shaferab** [stschiff/msmc2#38]
HI,

I'm having a difficult time interpreting my relative cross-coalescence rate in light of my MSMC2 plots and what I see online. It's raising a red flag, but wanted your take. Note, for ccr I used -I 0,4 and -P 0,1 combined; I've seen -I 0-4 as syntax but that is not accepted in my verssion. I've also followed the MSMC2 guideliine and the genome is decent.  My Ne plots look similar to our PSMC runs on the genome, but we see a seperation happening >100 KYA (below), consequently the CCR is all over the map. This is a very dynamic species due to glaciations and multiple refugia but hoping for first thoughts / red flags from yourself or the community. Thanks
![Screen Shot 2022-03-24 at 10 17 37 AM](https://user-images.githubusercontent.com/8352066/159936449-bb5b5a59-a8f9-448c-97a3-492242d70b6b.png)
![Screen Shot 2022-03-24 at 10 17 59 AM](https://user-images.githubusercontent.com/8352066/159936507-8fc43800-f90b-4710-81b6-29eefbb96671.png)
,

**Comment by shaferab** [comment]
Thanks.  One last follow up; could one interpretation of the NE plots AND full CCR being divergent lineages merging ~400 KYA, then seperating again 30 KYA?

**Comment by stschiff** [comment]
Perhaps, but your Ne plots are from PSMC, and the CCR from MSMC2, if I understand correctly. I would rather want to see the two from the same method to judge.

**Comment by stschiff** [comment]
Ah OK... Hmm, I don't think there is much support for a split around 400kya from the MSMC results. Yes, the Ne-curves look a bit divergent, but it's also clearly towards the right end of the resolution, and the CCR doesn't show that (the CCR going "up" as you move left on the right end of the plot is an artefact, there is no theory support for the CCR going up forward in time). I think the autosomal genome in this case supports a recent separation. Have you tried other methods, perhaps based on SFS, like momi2 or dadi to get independent on more model-based estimates of the divergence?

**Comment by shaferab** [comment]
Yes, dadi supports a very recent split, consistent with the CCR not mtDNA.  I think, naively, I assumed a split would manifested in the Ne plots as well once they are diverged.

**Comment by shaferab** [comment]
Here's how it looks across pops zoomed in. Thanks again, can probably close now!
![Screen Shot 2022-03-26 at 10 43 38 AM](https://user-images.githubusercontent.com/8352066/160244578-6996b4d7-fed5-4f0d-8a0a-e5abc4287beb.png)

**Comment by stschiff** [comment]
Yeah, OK, looks pretty clear like a recent split to me. OK, I'll close, thanks for sharing!
