### ISSUE TITLE
Problem running msmc2 with more than one scaffold

### ISSUE THREAD

**Issue by micadiz** [stschiff/msmc2#39]
Hi,

I have some issues running msmc2 in SNP data generated from a draft assembly of a nonmodel genome.

When I tested msmc2 using _one scaffold_, I obtained the three out files (t2_vsd.msmc2.final.txt,  t2_vsd.msmc2.log,  t2_vsd.msmc2.loop.txt) 
`msmc2 -p 1*2+15*1+1*2 -o ${outresult}/t2_vsd.msmc2 -I 0,1,2,3,4,5,6,7,8 scaffold_37.msmc2.input`

However, when I execute msmc2 using _more than one scaffold_:
`msmc2 -t 4 -s -o ${outresult}/t3_vsd.msmc2 -I 0,1,2,3,4,5,6,7,8 scaffold_37.msmc2.input scaffold_38.msmc2.input`

I obtain an error, and the software does not generate the **msmc2.final.txt** file.
This is the stack of errors I obtain from the execution:
```
??:? _d_arraybounds_indexp [0x6373ad]
??:? void model.psmc_hmm.PSMC_hmm.runForward() [0x59716d]
??:? std.typecons.Tuple!(double[][], double[][2], double).Tuple expectation_step.singleChromosomeExpectation(in model.data.SegSite_t[], ulong, in model.propagation_core.PropagationCore
??:? int expectation_step.getExpectation(in model.data.SegSite_t[][], model.psmc_model.PSMCmodel, ulong, ulong).__foreachbody13(ulong, ref const(model.data.SegSite_t[])) [0x5ccde0]
??:? void std.parallelism.ParallelForeach!(const(model.data.SegSite_t[])[]).ParallelForeach.opApply(scope int delegate(ulong, ref const(model.data.SegSite_t[]))).doIt() [0x578646]
??:? void std.parallelism.run!(void delegate()).run(void delegate()) [0x644c7f]
??:? void std.parallelism.Task!(std.parallelism.run, void delegate()).Task.impl(void*) [0x64475f]
??:? void std.parallelism.AbstractTask.job() [0x675686]
??:? void std.parallelism.TaskPool.doJob(std.parallelism.AbstractTask*) [0x643297]
??:? void std.parallelism.TaskPool.executeWorkLoop() [0x643406]
??:? void std.parallelism.TaskPool.startWorkLoop() [0x6433af]
??:? void core.thread.context.Callable.opCall() [0x664a9c]
??:? thread_entryPoint [0x66457a]
??:? [0x2ae3011b8ea4]
??:? clone [0x2ae301def9fc]
```

Thanks

**Comment by stschiff** [comment]
Hmm, are you sure this isn't an issue with your second scaffold file? Have you tried the second one individually? I suspect you have missing haplotypes somewhere, or some other issue with the second scaffold input data file.

**Comment by micadiz** [comment]
Thank you for your reply :) You were right, my problem was related to the input scaffold file
