### ISSUE TITLE
msmc2 installation problem

### ISSUE THREAD

**Issue by 5681** [stschiff/msmc2#40]
Dear Stephan,

I'm trying to install msmc2 and running into problems. I believe I correctly installed GSL library and DMD, which is activated.

The make command I run (within the msmc2-2.1.3 directory) gives me the following error:
**(dmd-2.100.0)Boni@Marias-MBP msmc2-2.1.3 % make
dmd -O /usr/local/lib/libgsl.a /usr/local/lib/libgslcblas.a -odbuild/test -ofbuild/release/msmc2 model/data.d model/gsl_matrix_vector.d model/propagation_core.d model/psmc_hmm.d model/psmc_model.d model/stateVec.d model/stateVecAllocator.d model/time_intervals.d model/transition_rate.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
model/propagation_core.d(129): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/propagation_core.d(142): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/propagation_core.d(156): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/propagation_core.d(174): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/propagation_core.d(226): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/psmc_hmm.d(122): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/psmc_hmm.d(188): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/psmc_hmm.d(204): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/psmc_hmm.d(240): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/psmc_hmm.d(258): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/time_intervals.d(99): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/time_intervals.d(110): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/time_intervals.d(127): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/transition_rate.d(103): Deprecation: Usage of the body keyword is deprecated. Use do instead.
model/transition_rate.d(122): Deprecation: Usage of the body keyword is deprecated. Use do instead.
maximization_step.d(152): Deprecation: Usage of the body keyword is deprecated. Use do instead.
maximization_step.d(163): Deprecation: Usage of the body keyword is deprecated. Use do instead.
maximization_step.d(183): Deprecation: Usage of the body keyword is deprecated. Use do instead.
maximization_step.d(201): Deprecation: Usage of the body keyword is deprecated. Use do instead.
clang: error: no such file or directory: '/usr/local/lib/libgsl.a'
clang: error: no such file or directory: '/usr/local/lib/libgslcblas.a'
Error: linker exited with status 1
make: *** [build/release/msmc2] Error 1
(dmd-2.100.0)Boni@Marias-MBP msmc2-2.1.3 % pwd**

I then edited the Makefile as follows to indicates where I installed the gsl libraries:
**# Set this variable to your static gsl libraries
GSLDIR=/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1
GSL={GSLDIR}/libgslcblas.a**

However, the problem is still not solved:
**maximization_step.d(201): Deprecation: Usage of the body keyword is deprecated. Use do instead.
clang: error: no such file or directory: '/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1/libgsl.a'
clang: error: no such file or directory: '/Users/Boni/Dropbox/SENCKENBERG/wild_cat_project/msmc/gsl/gsl-2.7.1/libgslcblas.a'
Error: linker exited with status 1
make: *** [build/release/msmc2] Error 1**

Any ideas how I could tackle this?

Best regards
ME

**Comment by Buffan3369** [comment]
Hi,

Stephan may probably provide a better answer than me, but I was faced with a similar issue, and just manually replacing each `body` command by a `do` one in each of the 5 problematic scripts (e.g. `model/propagation_core.d`, the problematic lines are indicated between parenthesis) apparently fixed it (I could run the msmsc-tools tutorial with no issue afterwards).

Hope it could help!
Cheers,
Lucas

**Comment by stschiff** [comment]
The deprecation warnings do not prevent compilation (although it's something I should take care of soon). The main issue here indeed is the fact that it can't find the GSL libraries. This is not something I can help with, as apparently the linker cannot find your GSL libraries. Have you checked that the two files (`libgsl.a` and `libgslcblas.a`) are indeed in the places you say they are?

**Comment by stschiff** [comment]
Deprecation warnings have been fixed in v2.1.4
