### ISSUE TITLE
wrong version displayed

### ISSUE THREAD

**Issue by EricDeveaud** [stschiff/msmc2#41]
Hello 
just installed msmc2 from 2.1.3 tagged archive and when called it display version`2.1.1` 

see:
```
msmc2 -h 
This is version 2.1.1. Usage: msmc2 [options] <datafiles>
```

regards

**Comment by stschiff** [comment]
Thanks for the catch, will look into it.

**Comment by stschiff** [comment]
Fixed in v.2.1.4
