### ISSUE TITLE
Cross-coalescence rate in multiple populations

### ISSUE THREAD

**Issue by BaiweiLo** [stschiff/msmc2#44]
Hi I am analyzing a data set of three populations, A, B, and C. A is the most basal of the three.

Based on ABBA BABA test, I know that A and B had gene flow. I could not tell whether A-C and B-C had gene flow from the current data.

My question is that if I want to know how gene flow between these populations change over time, is it reasonable to do cross-coalescence analysis on each population pair? For me it makes sense to do that between A and B. But I don't know if the introgressed region in A and/or B will confound the results when doing A-C and B-C cross-coalescence.

Thank you!

**Comment by stschiff** [comment]
Not sure whether I can help here. Try it out, I suggest. You will see that when analysing cross coalescence rates that it is sometimes not so straight forward to link it up with results from D statistics. It's also not directly interpretable as gene flow.
