### ISSUE TITLE
msmc2 install failed

### ISSUE THREAD

**Issue by jayramr** [stschiff/msmc2#46]
Hi Team,

I'm trying to install this package from source. I added dmd and gsl support still I'm getting below error. Please advise

```
make
dmd -O /usr/local/lib/libgsl.a /usr/local/lib/libgslcblas.a -odbuild/test -ofbuild/release/msmc2 model/data.d model/gsl_matrix_vector.d model/propagation_core.d model/psmc_hmm.d model/psmc_model.d model/stateVec.d model/stateVecAllocator.d model/time_intervals.d model/transition_rate.d powell.d brent.d maximization_step.d expectation_step.d msmc2.d logger.d
model/propagation_core.d(129): Error: Declaration expected, not 'do'
model/propagation_core.d(131): Error: Declaration expected, not 'foreach'
model/propagation_core.d(131): Error: Declaration expected, not '0'
model/propagation_core.d(133): Error: function declaration without return type. (Note that constructors are always named 'this')

model/psmc_hmm.d(129): Error: Declaration expected, not 'foreach'
model/psmc_hmm.d(129): Error: Declaration expected, not '1'
model/psmc_hmm.d(135): Error: Declaration expected, not 'else'
make: *** [Makefile:20: build/release/msmc2] Error 1
```

**Comment by jayramr** [comment]
dmd - 2.065.0
gsl - 2.7
GNU Make 4.3

**Comment by jayramr** [comment]
@stschiff Please check if you get time

**Comment by jayramr** [comment]
Actually I'm in the process of building this package under bioconda channel. So before that i need to check whether the manual installation works. 
Here is the recipe i build for this install https://github.com/bioconda/bioconda-recipes/pull/38469/files

Please advise on above error and how to fix this, so i will update my recipe and publish a conda package under bioconda channel

**Comment by jayramr** [comment]
Hi, 

Could someone please advise

**Comment by jayramr** [comment]
Hello, 

Could anyone please update on this ?

**Comment by stschiff** [comment]
Sorry for the silence. So, I can not reproduce this. No idea where it comes from... Would it help if I upload compiled executables?

**Comment by jayramr** [comment]
I tested this installation on Ubuntu 20.04 LTS base OS. 
```
dmd - 2.065.0
gsl - 2.7
GNU Make 4.3
```

Could you adivse what would be your base installar configuration/prerequisites ? 

If you include the compiled executables, in the source code also satisfies my requirement. Then I need to skip the make/compilation step in the conda recipe.

Please let me know once it is added, i will test

**Comment by stschiff** [comment]
OK, this might be due to a change in the D compiler recently. I'm using
```
dmd --version
DMD64 D Compiler v2.100.2
```

You might want to try a commit that predates this change, for example https://github.com/stschiff/msmc2/releases/tag/v2.1.3.

Download the source code from this tag and try again, please.

**Comment by jayramr** [comment]
@stschiff i tested with the latest version and smoothly installed without any issues
```
msmc2 v2.1.4 
dmd v2.101.2
gsl  2.7.1
```

Now I would need to build this on bioconda. It would be great if you can compile the next version with excecutables? Otherwise i need to add the latest version for dmd in conda-forge as these takes sometime to push to upstream.

Please let me know

**Comment by jayramr** [comment]
Hi, 

Could you get any chance to complile the excecutable and release as a new package. If this is possible i can easily move it as a bioconda package

**Comment by stschiff** [comment]
OK, I've just uploaded the latest execs to the release: https://github.com/stschiff/msmc2/releases/tag/v2.1.4

**Comment by jayramr** [comment]
Thanks @stschiff

**Comment by jayramr** [comment]
This is available now in bioconda 
https://anaconda.org/bioconda/msmc2

**Comment by stschiff** [comment]
Very cool, thank you! Have you tweeted about it? Shall I? Do you have a handle so I can credit you?

**Comment by jayramr** [comment]
I haven't tweeted and yes you can.
And I'm contributing packages in bioconda channel is for benefit for many peoples. Thanks for your kind words and no need any credits :)
