### ISSUE TITLE
Multiple Chromosome Problems

### ISSUE THREAD

**Issue by econdesousa** [stschiff/msmc2#5]
Dear Doctor Schiffels 
First of all congratulations for the great work.

I'm trying to apply your code for four individuals (2 of Population 1 and 2 of Population 2).

It all goes well when my data consists only in one chromosome, but when I try to use more (even for 2 chromosomes)  the code "msmc2 -s -o outDIR/POP1.msmc2 -I 0,1,2,3 outDIR/Pop1Pop2.multihetsep.txt" never passes the first "Expectation step". I believe, it is a memory problem.

Is there any way to compute the msmc2 output for each chromosome separately and combine the results (only) at the end?

Thanks

PS: the file outDIR/Pop1Pop2.multihetsep.txt was generated in two runs of generate_multihetsep.py (one for each chrom) and then concatenated.

**Comment by stschiff** [comment]
You have to give the chromosome files separately:

msmc2 <options> input_chr1.txt input_chr2.txt …

It will jointly analyse them and produce a single output.

Best,
Stephan

P.S. Consider joining our mailing list:
https://groups.google.com/forum/#!forum/msmc-popgen
