### ISSUE TITLE
How to deal with InDels?

### ISSUE THREAD

**Issue by econdesousa** [stschiff/msmc2#6]
Dear doctor Schiffels

Thanks for your last answer (issue #5: Multiple Chromosome Problems). I can run msmc2 with no problems now.

Nevertheless, I’m thinking about one issue that I don’t know how to deal with (and, mainly, how msmc2 deal with).
Consider a given locus with an insertion, for example Ref=G and Alt=GT.
If I have two samples, one 0|1 and the other 0|0 (VCF style notation), after run generate_multihetsep.py the resulting file will have a line like:

chr1    44268191    124    GGTGG

So, instead of 4 haplotypes for 2 samples it “looks like” we have 5. I understand why it looks like this, but my point is, does msmc2 “understands” it? What should be the best way to deal with InDels?

• Should we let the multihetsep file keep them and run msmc2 without thinking about it? 

• Should we pass a filter through the file and remove all the lines with “ambiguous number of haplotypes” (in this case all lines where column 4 have length different than 4)?

• Other?

Thanks

**Comment by stschiff** [comment]
You cannot use Indels with MSMC. Please remove indels before running generate_multihetsep.py.

Stephan

**Comment by econdesousa** [comment]
Thanks.
But aren’t we introducing a potential errors by simply removing indels before running generate_multihetsep.py?

Here’s an example (that happens whenever all the samples have an indel in the same locus):

Running generate_multihetsep.py WITH indels in the vcf I get:

chr1       460161       1       GCCG
chr1       460166       5       ACAACAAAACAACA
chr1       460180       14      ATTA

Running generate_multihetsep.py WITHOUT indels in the vcf I get:

chr1       460161       1       GCCG
chr1       460180       19      ATTA

As you said in the help, “The third column contains the number of called sites since the previous segregating site, including the current site. (…) This is very important for MSMC, because it would otherwise assume that there was a huge homozygous segment spanning from 1 through 68306.”

In the example above the homozygous segment is not huge, it has length 14 and it would be considered as having length 19 if indels were removed previouly, but it could be larger if several indels exist without any SNPs in between.

Wouldn’t be better to remove the line “chr1       460166       5       ACAACAAAACAACA” from the multihetsep file instead of removing the indels from the vcf? Either way we will get only an approximation of the result, but in one option we are changing true data while in other we are omitting data. 
Which one of the alternatives would be closer to the reality?

A different approach could be replacing in the VCF file the alternative by a different one. In the example above, Ref=A and Alt= ACAACA. If I replace Alt= ACAACA by, for example, Alt= C the resulting file would be 
chr1       460161       1       GCCG
chr1       460166       5       ACCA
chr1       460180       14      ATTA

Wouldn’t the final result be an even better approximation when compared with either of the proposed alternatives?Does the msmc output depend on the true value of Ref and Alt or simply about the size of the homozygous segment? In other words, would be a problem if I choose as Alt an C or a G or a T (providing it must be different from the Ref=A)?

Thanks

**Comment by stschiff** [comment]
Hi, 
I don’t think it’s a problem, but I’ve never given much thought to Indels at all. I simply followed the same processing steps as in PSMC (Li and Durbin 2011), who simply removed Indels already at the calling stage. I don’t have time to investigate this, so if you have an idea how to deal with them better, please go ahead!

If you want to discuss this with the community, please join my mailing list: https://groups.google.com/forum/#!forum/msmc-popgen <https://groups.google.com/forum/#!forum/msmc-popgen>

Best,
Stephan
