### ISSUE TITLE
failure to run msmc2 on single sample

### ISSUE THREAD

**Issue by vicenciooostra** [stschiff/msmc2#7]
Hi Stephan,

I am trying to run msmc2 but am getting an error. I did successfully generate the input files using bamcaller.py and generate_multihetsep.py. I've also tried msmc2 on the tutorial data (EUR_AFR.chr1.multihetsep.txt from MSMC-tutorial-files.zip in https://oc.gnz.mpg.de/owncloud/index.php/s/786PRKqWBYXm0YT/download) and that worked fine, so my installation and compilation seem OK. I have several populations with 5 individuals in each, but to keep things simple I first wanted to try a single individual from one population. I prepared data from that individual for one chromosome, unphased, from the original bam file (see below this message for those steps). I realise I need to phase my samples but figured that for a single individual I would first try unphased. Also, I currently don't have a mappability mask as I am working on a non-model species (but I am trying to get SNPable Regions to work).

Any help would be much appreciated!
Best regards,
Vicencio

I ran the command like this
msmc2 -o my_msmc_output J001_NC_024351.1.txt

and it gave me this error
## error in parsing command line: object.Exception@model/data.d(57): Enforcement failed

??:? pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x544a89]
??:? @safe std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch std.exception.enforce!(Exception, std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch).enforce(std.regex.__T10RegexMatchTAxaS453std5regex8internal8thompson15ThompsonMatcherZ.RegexMatch, lazy const(char)[], immutable(char)[], ulong) [0x55e6ae]
??:? void model.data.checkDataLine(const(char[])) [0x535745]
??:? ulong model.data.getNrHaplotypesFromFile(immutable(char)[]) [0x53582c]
??:? void msmc2.parseCommandLine(immutable(char)[][]) [0x58969b]
??:? _Dmain [0x58924f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x5e1ece]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x5e1e18]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x5e1e8a]
??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x5e1e18]
??:? _d_run_main [0x5e1d89]
??:? main [0x5925f5]
??:? __libc_start_main [0xbd6e8f44]

input data:
head J001_NC_024351.1.txt
NC_024351.1 126 14  TC
NC_024351.1 175 48  GA
NC_024351.1 228 53  TC
NC_024351.1 438 207 TC
NC_024351.1 448 10  TG
NC_024351.1 544 95  CT
NC_024351.1 674 59  TG
NC_024351.1 711 37  CG
NC_024351.1 777 66  AG
NC_024351.1 1235    43  GA

data preparation from bam file:
samtools mpileup -q 20 -Q 20 -C 50 -u -r NC_024351.1 -f ref_genome.fasta J001.bam | bcftools call -c -V indels | ./bamCaller.py 24 J001_NC_024351.1_mask.bed.gz | gzip -c > J001_NC_024351.1.vcf.gz

./generate_multihetsep.py --mask=J001_NC_024351.1_mask.bed.gz J001_NC_024351.1.vcf.gz > J001_NC_024351.1.txt

The vcf contains 124,468 SNPs, and the final input file J001_NC_024351.1.txt contains 74,988 SNPs.

**Comment by vicenciooostra** [comment]
Just a quick update--I slightly changed the command to select haplotypes (though that shouldn't be necessary), and now it does work:
msmc2 -I 0,1 -o my_msmc_output J001_NC_024351.1.txt

Is this a correct command? 

My output looks like this:
time_index	left_time_boundary	right_time_boundary	lambda
0	0	3.044e-05	1881.41
1	3.044e-05	6.60473e-05	1881.41
2	6.60473e-05	0.000107699	3431.25
3	0.000107699	0.000156421	698.316
4	0.000156421	0.000213413	485.438
5	0.000213413	0.00028008	400.064
6	0.00028008	0.000358064	305.043
7	0.000358064	0.000449285	243.447
8	0.000449285	0.000555991	224.855
9	0.000555991	0.000680811	238.564
10	0.000680811	0.000826818	272.882
11	0.000826818	0.000997611	311.893
12	0.000997611	0.0011974	343.286
13	0.0011974	0.00143109	364.706
14	0.00143109	0.00170446	382.405
15	0.00170446	0.00202423	405.324
16	0.00202423	0.00239829	435.193
17	0.00239829	0.00283584	467.417
18	0.00283584	0.00334766	498.561
19	0.00334766	0.00394636	526.686
20	0.00394636	0.0046467	556.179
21	0.0046467	0.00546591	594.418
22	0.00546591	0.00642419	640.021
23	0.00642419	0.00754514	687.026
24	0.00754514	0.00885637	716.343
25	0.00885637	0.0103902	720.008
26	0.0103902	0.0121843	752.971
27	0.0121843	0.0142831	916.708
28	0.0142831	0.0167381	916.708
29	0.0167381	0.0196098	115054
30	0.0196098	0.022969	115054
31	0.022969	inf	115054


And the first bit of the log file looks thus:
input files:         ["J001_NC_024351.1.txt"]
maxIterations:       20
mutationRate:        0.00179323
recombinationRate:   0.000448307
timeSegmentPattern:  [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3]
nrThreads:           8
outFilePrefix:       my_msmc_output
hmmStrideWidth:      1000
fixedRecombination:  false
initialLambdaVec:    []
skipAmbiguous:       false
indices:             [0, 1]
logging information written to my_msmc_output.log
loop information written to my_msmc_output.loop.txt
final results written to my_msmc_output.final.txt
time factor:         1
[1/20] Baumwelch iteration
  * [1/1] Expectation Step, log likelihood: -469107
  * [3/200(max)] Maximization Step, Q-function before: 622.141, after:621.931

**Comment by stschiff** [comment]
Thanks for reporting. This looks like a bug. I agree with you that it shouldn’t be necessary to select haplotypes. I’ll look into it.

Good that you managed to get results anyway.
Stephan

**Comment by vicenciooostra** [comment]
Hi Stephan,

thanks very much for your answer. For one sample indeed I managed to get results. However when trying to do multiple samples in two populations I run into trouble. 

I manage to get my analyses running within each population (n=5 each) with the following commands:
msmc2 -I 0,1,2,3,4,5,6,7,8,9 -o pop1.NC_024351.1.txt -s NC_024351.1.txt
msmc2 -I 10,11,12,13,14,15,16,17,18,19 -o pop2.NC_024351.1.txt -s NC_024351.1.txt

This is giving me sensible results for each population separately. However when I try to estimate cross-coalescence rates msmc2 doesn’t accept my command:
msmc2 -P 0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1 -o across.NC_024353.1.txt -s NC_024353.1.txt
It immediately (before loading any file) gives me the following error:
error in parsing command line: object.Exception@model/data.d(57): Enforcement failed

I've posted a longer description of my problem in the msmc-popgen google group:
https://groups.google.com/forum/#!topic/msmc-popgen/WWcz96uR9Ho

Best regards,
Vicencio

**Comment by stschiff** [comment]
These are a LOT of chromosomes. I would suggest you try 4 haplotypes first, then 8 at most. More than 8 is already quite huge and for some reason sometimes results in overfitting and divergences.

Stephan

**Comment by vicenciooostra** [comment]
Hi,

I forgot to mention that I get the same errors when just trying 4 haplotypes. The first two comands work, the third one immediately (before loading any file) gives me the same error:
msmc2 -I 0,1 -o J001_J031_NC_024351.1_within_J001 -s J001_J031_NC_024351.1.txt
msmc2 -I 2,3 -o J001_J031_NC_024351.1_within_J031 -s J001_J031_NC_024351.1.txt
msmc2 -P 0,0,1,1 -o J001_J031_NC_024351.1_across J001_J031_NC_024351.1.txt
error in parsing command line: object.Exception@model/data.d(57): Enforcement failed

Cheers,
Vicencio

**Comment by vicenciooostra** [comment]
I've tried using the pre-compiled binary (https://github.com/stschiff/msmc2/releases/download/v2.0.0/msmc_2.0.0_linux64bit) instead of compiling myself, but I got the same error when trying to compute cross-coalescence rates for four haplotypes:
msmc2 -P 0,0,1,1 -o J001_J031_NC_024351.1_across J001_J031_NC_024351.1.txt
error in parsing command line: object.Exception@model/data.d(57): Enforcement failed

**Comment by stschiff** [comment]
This error suggests that you have an invalid input file. Please have a look at the documentation for the format and see whether your input files conforms to what it should.
