### ISSUE TITLE
Likelihood sometimes decreases?

### ISSUE THREAD

**Issue by bredelings** [stschiff/msmc2#8]
Hi,

I'm running MSMC, but have been wondering why the likelihood sometimes gets worse.

Here is an example -- see iteration 12:

[1/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -84540.1
  * [2/200(max)] Maximization Step, Q-function before: 106.09, after:104.708
[2/30] Baumwelch iteration
  * [2/3] Expectation Step, log likelihood: -82284.3
  * [2/200(max)] Maximization Step, Q-function before: 106.52, after:106.381
[3/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81987.4
  * [2/200(max)] Maximization Step, Q-function before: 108.191, after:108.158
[4/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81879.8
  * [2/200(max)] Maximization Step, Q-function before: 110.05, after:110.034
[5/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81826.8
  * [2/200(max)] Maximization Step, Q-function before: 111.965, after:111.954
[6/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81797.3
  * [2/200(max)] Maximization Step, Q-function before: 113.887, after:113.878
[7/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81778.5
  * [2/200(max)] Maximization Step, Q-function before: 115.798, after:115.791
[8/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81765
  * [2/200(max)] Maximization Step, Q-function before: 117.695, after:117.688
[9/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81754.4
  * [2/200(max)] Maximization Step, Q-function before: 119.575, after:119.569
[10/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81745.7
  * [2/200(max)] Maximization Step, Q-function before: 121.441, after:121.435
[11/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81738.2
  * [2/200(max)] Maximization Step, Q-function before: 120.556, after:120.273
[12/30] Baumwelch iteration
  * [2/3] Expectation Step, log likelihood: -82405.7
  * [2/200(max)] Maximization Step, Q-function before: 126.089, after:126.011
[13/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -82056.5
  * [2/200(max)] Maximization Step, Q-function before: 127.496, after:127.469
[14/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81892
  * [2/200(max)] Maximization Step, Q-function before: 129.167, after:129.155
[15/30] Baumwelch iteration
  * [3/3] Expectation Step, log likelihood: -81806.3
  * [2/200(max)] Maximization Step, Q-function before: 130.934, after:130.928

**Comment by bredelings** [comment]
Here's an example file for you.  I get:

read 7742 SNPs from file chr14-4way.msmc, using indices [[0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3]]
estimating mutation rate: 0.000673106
input files:         ["chr14-4way.msmc"]
maxIterations:       20
mutationRate:        0.000673106
recombinationRate:   0.000168276
timeSegmentPattern:  [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3]
nrThreads:           12
outFilePrefix:       
hmmStrideWidth:      1000
fixedRecombination:  false
initialLambdaVec:    []
skipAmbiguous:       false
indices:             [0, 1, 2, 3]
logging information written to .log
loop information written to .loop.txt
final results written to .final.txt
time factor:         1
[1/20] Baumwelch iteration
  * [4/6] Expectation Step, log likelihood: -173481
  * [2/200(max)] Maximization Step, Q-function before: 298.065, after:286.173
[2/20] Baumwelch iteration
  * [4/6] Expectation Step, log likelihood: -167038
  * [2/200(max)] Maximization Step, Q-function before: 271.804, after:267.719
[3/20] Baumwelch iteration
  * [5/6] Expectation Step, log likelihood: -167611
  * [2/200(max)] Maximization Step, Q-function before: 263.519, after:260.609
[4/20] Baumwelch iteration
  * [5/6] Expectation Step, log likelihood: -169469
  * [2/200(max)] Maximization Step, Q-function before: 266.326, after:265.117
...

[chr14-4way.msmc.txt](https://github.com/stschiff/msmc2/files/835302/chr14-4way.msmc.txt)

**Comment by bredelings** [comment]
This file is a bit more well-behaved, for reference.

[chr14-3way.msmc.txt](https://github.com/stschiff/msmc2/files/835311/chr14-3way.msmc.txt)

**Comment by stschiff** [comment]
This can happen because of the coarse-graining of the empirical transition matrix. It typically means that it is overfitting. You seem to have input only one chromosome, which is too little data. Have you tried an entire genome?

**Comment by bredelings** [comment]
My entire genome is only 24 megabases, so a bit smaller than human.  I have tried up to 2 chromosomes, and the problem still persists.  I will get back to you after adding a few more chromosomes.

My impression of what you are saying is that the baum-welch algorithm is correctly optimizing a likelihood which assumes that coalescence times occur exactly in the middle of the interval boundaries?  And so optimizing this likelihood may not optimize the real (less approximate) likelihood which allows the coalescence time to occur anywhere which an interval?

**Comment by bredelings** [comment]
I'm generating the multi-het-sep files from fasta alignments, and I've realized that the ends of the chromosomes contain tons of (possibly bad) SNPs for this species (malaria).  So, I've needed to clean them a bid.  Theta seems to be about 0.001 or 0.0011

Here are my latest 2 files.  The chr14 one (which has more SNPs) does not work, but the chr13 one does work.

[chr13-3way-fsa.msmc.txt](https://github.com/stschiff/msmc2/files/887709/chr13-3way-fsa.msmc.txt)
Length changed from 1780001 to 1582555
Masked 0 sites.
Sites with 2 alleles: 2675 (0.001690304602)  Sites with 3 alleles: 3 (1.895668713e-06)  
Variant sites: 2678 (0.001692200271)  Variant sites at distance 1 before variant: 98
Informative sites: 0 (0)  

found 3 haplotypes in file
processing file chr13-3way-fsa.msmc
called sites	1581279
segregating sites	2678
sites with ambiguous phase	0
pairwise hets(0,1)	1600
pairwise hets(0,2)	1830
pairwise hets(1,2)	1929
Tajima's theta	0.00112968
Watterson's theta	0.00112904


[chr14-3way.msmc.txt](https://github.com/stschiff/msmc2/files/887711/chr14-3way.msmc.txt)
 Length changed from 2900001 to 2838749
 Masked 0 sites.
 Sites with 2 alleles: 4277 (0.001506649584)  Sites with 3 alleles: 5 (1.761339238e-06)  
 Variant sites: 4282 (0.001508410923)  Variant sites at distance 2 before variant: 111
 Informative sites: 0 (0)  

 found 3 haplotypes in file
 processing file chr14-3way.msmc
 called sites	2838132
 segregating sites	4282
 sites with ambiguous phase	0
 pairwise hets(0,1)	2975
 pairwise hets(0,2)	3032
 pairwise hets(1,2)	2562
 Tajima's theta	0.00100641
 Watterson's theta	0.00100583

**Comment by stschiff** [comment]
No, the transition probabilities in the HMM do not assume a mid-point coalescence time, but integrate the times within each interval. Again, you need to input a LOT more data for MSMC to work. A few thousand SNPs are not enough. I am not sure this will eventually work with Malaria, but the only chance you have is inputting all the data at once, as in "msmc <options> <input_file_chr1> <input_file_chr2>..."

Stephan
