### ISSUE TITLE
Relative cross coalescence rate larger than 1

### ISSUE THREAD

**Issue by silvewheat** [stschiff/msmc2#9]
excuse me,
       I use msmc2 to calculate divergence time according to the guide, but in some of my result, there are relative cross coalescence rate larger than 1, I wonder why, and how to deal with it. Thanks!

**Comment by stschiff** [comment]
Try MSMC, it bounds the relative cross coalescence rate between 0 and 1. Application of MSMC2 for obtaining cross-population results is not yet final.

Best,
Stephan

**Comment by silvewheat** [comment]
Thank you very much, I will try that.

**Comment by guzhongru** [comment]
Hi Stephan
I also met this problem. I also tried msmc and msmc2, but the results are different. So, how to choose the result ?
